---
title: "EDA buscas"
output: html_notebook
---

O objeto principal da análise são as buscas e a navegação depois da busca. Criamos esses dados a partir dos dados originais da wikimedia em `/data/search_data.csv`. 

Aqui, exploramos esses dados. 

```{r setup}
library(tidyverse)
library(here)
library(lubridate)
library(boot)
theme_set(theme_bw())
```

```{r ETL}
buscas = read_csv(here::here("data/search_data.csv"))
names(buscas)[names(buscas) == "session_start_date"] <- "search_time"

```

```{r}

buscas.por.sessao <- buscas %>% group_by(session_id, group) %>% 
    summarise(session_length = first(session_length), 
              search_time = first(search_time), 
              sum_clicks = sum(num_clicks),
              sum_results = sum(results)) %>%
    ungroup()

theta_diff_rate = function(buscas, i){
    rates = buscas %>%
        slice(i) %>%
        group_by(group) %>% 
        summarise(rate = sum(sum_clicks > 0)/n()) 
    
    group.a = rates %>% filter(group == "a") %>% pull(rate)
    group.b = rates %>% filter(group == "b") %>% pull(rate)
    
    group.a - group.b
}

theta_embaralhado = function(buscas){
    rates = buscas %>% 
        mutate(grupo_embaralhado = sample(group, n())) %>% 
        group_by(grupo_embaralhado) %>% 
        summarise(rate = sum(sum_clicks > 0)/n()) 
    
    group.a = rates %>% filter(grupo_embaralhado == "a") %>% pull(rate)
    group.b = rates %>% filter(grupo_embaralhado == "b") %>% pull(rate)
    
    group.a - group.b
}

theta_embaralhado(buscas.por.sessao)
theta_diff_rate(buscas.por.sessao, 1:NROW(buscas.por.sessao))

diffs1 = replicate(2000, {theta_embaralhado(buscas.por.sessao)})

tibble(diferenca = diffs1) %>% 
  ggplot(aes(x = diferenca)) +  
    geom_density(fill = "white", color = "darkgreen") + 
  geom_vline(xintercept = theta_diff_rate(buscas.por.sessao, 1:NROW(buscas.por.sessao)), 
             color = "orange") + 
    geom_vline(xintercept = - theta_diff_rate(buscas.por.sessao, 1:NROW(buscas.por.sessao)), 
             color = "orange") + 
    geom_rug()

p.value <- mean(abs(diffs1) >= abs(theta_diff_rate(buscas.por.sessao, 1:NROW(buscas.por.sessao))))

p.value

```



```{r}

buscas = buscas %>%
    group_by(group, session_id)%>%
    summarise(clicked = if_else(max(num_clicks) > 0, T,F), zero_resoult = if_else(max(results) == 0, T,F))

buscas    

```

#clickthrough_rate

```{r}

funcao_theta_clickthrough_rate = function(d, i) {
  
    d1 = d%>% slice(i)
  
    total_group = d1 %>% 
                  group_by(group)%>% 
                  summarise(amount = n())
  
    total_group_clicked = d1 %>% 
                          filter(clicked == T) %>% 
                          group_by(group) %>% 
                          summarise(amount_clicked = n())
  
    join = total_group %>% 
           inner_join(total_group_clicked, by="group") %>% 
           mutate(prop = amount_clicked/amount)
  
    prop_a = join %>% filter(group == "a") %>% pull(prop)
    prop_b = join %>% filter(group == "b") %>% pull(prop)
  
    return (prop_a - prop_b)
}

theta_clickthrough_rate = funcao_theta_clickthrough_rate(buscas, 1:NROW(buscas))
```


```{r}
booted <- boot(data = buscas,
               statistic = funcao_theta_clickthrough_rate,
               R = 200)
intervalo_calc <- boot.ci(booted, conf=.95, type="bca")
intervalo_calc

```

```{r}
theta_embaralhado = function(d){
    
    sonos = d %>% 
        mutate(grupo_embaralhada = sample(group, n())) %>% 
        group_by(grupo_embaralhada) %>% 
        summarise(clickthrough_rate = mean(sono_fds)) 
    
    cdd = sonos %>% filter(turma_embaralhada == "cdd") %>% pull(sono)
    fpcc = sonos %>% filter(turma_embaralhada == "fpcc") %>% pull(sono)
    
    cdd - fpcc
}
theta_embaralhado(dados)
```



```{r}

diffs1 = replicate(5000, {theta_embaralhado(buscas)})

tibble(diferenca = diffs1) %>% 
  ggplot(aes(x = diferenca)) + 
  # geom_histogram(binwidth = .2, fill = "white", color = "darkgreen") + 
    geom_density(fill = "white", color = "darkgreen") + 
  geom_vline(xintercept = theta_diferenca_fds(dados, 1:NROW(dados)), 
             color = "orange") + 
    geom_vline(xintercept = - theta_diferenca_fds(dados, 1:NROW(dados)), 
             color = "orange") + 
    geom_rug()
```

```{r}

mean(abs(diffs) >= abs(theta_diferenca_fds(dados, 1:NROW(dados))))

```


#zeroResults_rate

```{r}

theta_diff_zero_results_rate = function(buscas, i){
    zero_results_rates = buscas %>%
        slice(i) %>%
        group_by(group) %>% 
        summarise(zero_results_rate = sum(results == 0)/n()) 
    
    group.a = zero_results_rates %>% filter(group == "a") %>% pull(zero_results_rate)
    group.b = zero_results_rates %>% filter(group == "b") %>% pull(zero_results_rate)
    
    group.a - group.b
}

theta_embaralhado_zero_results = function(buscas){
    zero_results_rates = buscas %>% 
        mutate(grupo_embaralhado = sample(group, n())) %>% 
        group_by(grupo_embaralhado) %>% 
        summarise(zero_results_rate = sum(results == 0)/n()) 
    
    group.a = zero_results_rates %>% filter(grupo_embaralhado == "a") %>% pull(zero_results_rate)
    group.b = zero_results_rates %>% filter(grupo_embaralhado == "b") %>% pull(zero_results_rate)
    
    group.a - group.b
}

theta_embaralhado_zero_results(buscas)

theta_diff_zero_results_rate(buscas, 1:NROW(buscas))

diffs_zero_results = replicate(2000, {theta_embaralhado_zero_results(buscas)})

p.value <- mean(abs(diffs_zero_results) >= abs(theta_diff_zero_results_rate(buscas, 1:NROW(buscas))))

p.value

```


```{r}

funcao_theta_zeroResults_rate = function(d, i) {
  
  d1 = d%>% slice(i)
  
  total_group = d1 %>% 
                group_by(group) %>% 
                summarise(amount = n())
  
  total_group_zero_resoult = d1 %>% 
                             filter(zero_resoult == T) %>% 
                             group_by(group) %>% 
                             summarise(amount_zero_resoult = n())
  
  join = total_group %>% 
         inner_join(total_group_zero_resoult, by="group") %>% 
         mutate(prop = amount_zero_resoult/amount)
  
  prop_a = join %>% filter(group == "a") %>% pull(prop)
  prop_b = join %>% filter(group == "b") %>% pull(prop)
  
  return (prop_a - prop_b)
}

theta_zeroResults_rate = funcao_theta_zeroResults_rate(buscas, 1:NROW(buscas))
```

```{r}
booted <- boot(data = buscas,
               statistic = funcao_theta_zeroResults_rate,
               R = 200)
intervalo_calc <- boot.ci(booted, conf=.95, type="bca")
intervalo_calc

```

